# 개발자 닉네임: _____R
# 개발자 디스코드: _R#8668
# 최신버전 다운로드 주소1:  https://www.spigotmc.org/resources/skript-addon-sketcr.83787/
# 최신버전 다운로드 주소2:  https://forums.skunity.com/resources/sketcr.1227/

# 아이디어 뱅크: 짖지리#6654 ( 블로그 : https://blog.naver.com/pseongsil/)


Packet: true
# true일 경우 패킷 관련 구문을 사용하실 수 있습니다